package net.anzop.gather.model.financials

import net.anzop.gather.model.SourceDataParams

data class Financials(
    val sourceDataSettings: SourceDataParams,
    val reportPeriod: ReportPeriod,
    val currency: String,
    val revenue: Long?,
    val costOfRevenue: Long?,
    val grossProfit: Long?,
    val operatingIncome: Long?,
    val totalAssets: Long?,
    val totalCurrentAssets: Long?,
    val prepaidExpenses: Long?,
    val propertyPlantAndEquipmentNet: Long?,
    val retainedEarnings: Long?,
    val otherAssetsNonCurrent: Long?,
    val totalNonCurrentAssets: Long?,
    val totalLiabilities: Long?,
    val shareholderEquity: Long?,
    val netIncome: Long?,
    val sharesOutstandingDiluted: Long?,
    val sharesOutstandingBasic: Long?,
    val epsDiluted: Double?,
    val epsBasic: Double?,
    val operatingCashFlow: Long?,
    val investingCashFlow: Long?,
    val financingCashFlow: Long?,
    val netCashFlow: Long?,
    val researchDevelopmentExpense: Long?,
    val sellingGeneralAdministrativeExpense: Long?,
    val operatingExpenses: Long?,
    val nonOperatingIncome: Long?,
    val preTaxIncome: Long?,
    val incomeTax: Long?,
    val depreciationAmortization: Long?,
    val stockBasedCompensation: Long?,
    val dividendsPaid: Long?,
    val cashOnHand: Long?,
    val currentNetReceivables: Long?,
    val inventory: Long?,
    val totalCurrentLiabilities: Long?,
    val totalNonCurrentLiabilities: Long?,
    val longTermDebt: Long?,
    val totalLongTermLiabilities: Long?,
    val goodwill: Long?,
    val intangibleAssetsExcludingGoodwill: Long?,
)
